# Generated by Django 3.2 on 2022-02-09 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220208_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='wallet_tag',
            field=models.CharField(default='9RlgJ5Hnf2yOq3q0', max_length=16, unique=True),
        ),
    ]
