# Generated by Django 3.2 on 2022-02-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220209_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='wallet_tag',
            field=models.CharField(default='sP2UWi6huGhWH8lZ', max_length=16, unique=True),
        ),
    ]
