# Generated by Django 3.2 on 2022-02-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220212_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='wallet_tag',
            field=models.CharField(default='iUgNI2aFsNDAgBZ9', max_length=16, unique=True),
        ),
    ]
