# Generated by Django 3.2 on 2022-02-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220216_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='wallet_tag',
            field=models.CharField(default='MMLqROxZsFsbbcCk', max_length=16, unique=True),
        ),
    ]
